[workspace]
members = ["canisters/dendrite", "crates/dendrite-types", "crates/ic-clients", "tools/xtask"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/aodl/NNS_Dendrite_Standard"
rust-version = "1.94.1"

[workspace.dependencies]
candid = "=0.10.24"
hex = "=0.4.3"
ic-cdk = "=0.20.2"
ic-asset-certification = "=3.2.0"
ic-http-certification = "=3.2.0"
include_dir = "=0.7.4"
serde = { version = "=1.0.228", features = ["derive"] }
pocket-ic = "=15.0.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"
