import test from "node:test";
import assert from "node:assert/strict";
import { parseNeuronId, formatNeuronId, OMEGA_REJECT_NEURON_ID } from "../src/ids.js";
import { authorityFor, canAddHotKey } from "../src/authority.js";
import { buildNeuronManagementProposal, commandAvailability, projectedFollowing, quorum, simulateThenSubmit } from "../src/proposals.js";
import { classifyReceiver } from "../src/rewards.js";
import { errorMessage, hexDigest, variantName } from "../src/compliance-view.js";
import { canisterIdFromHostname, createAnonymousActor } from "../src/actor.js";
import { clear, element, safeHttpsLink } from "../src/dom.js";
import { renderSnapshot } from "../src/compliance-view.js";

test("u64 IDs round trip without Number", () => { const id = parseNeuronId(OMEGA_REJECT_NEURON_ID); assert.equal(typeof id, "bigint"); assert.equal(formatNeuronId(id), OMEGA_REJECT_NEURON_ID); });
test("malformed IDs fail closed", () => { for (const id of ["", "0", "01", "+1", "-1", " 1", "1 ", "1.0", "1e2", "18446744073709551616"]) assert.throws(() => parseNeuronId(id)); });
test("authority is exact controller or hotkey only", () => { assert.equal(authorityFor("p1", { controller:["p1"], hot_keys:[] }), "controller"); assert.equal(authorityFor("p1", { controller:["p2"], hot_keys:["p1"] }), "hotkey"); assert.equal(authorityFor("p1", { controller:["p2"], hot_keys:[], visibility:"public" }), null); assert.equal(canAddHotKey("hotkey"), false); });
test("authority accepts Principal-like values and alternate hot-key spelling", () => { const principal={toText:()=>"p1"}; assert.equal(authorityFor("p1",{controller:[principal]}),"controller"); assert.equal(authorityFor("p1",{hotKeys:[principal]}),"hotkey"); assert.equal(authorityFor("p1",{}),null); assert.equal(canAddHotKey("controller"),true); });
test("quorum uses equal manager ballots", () => { assert.equal(quorum(5), 3); assert.equal(quorum(15), 8); });
test("nested request preserves both neuron layers", () => { const r = buildNeuronManagementProposal({ proposerId:"11", targetId:"22", title:"Refresh", summary:"Refresh voting power", command:{kind:"RefreshVotingPower"} }); assert.equal(r.id[0].id, 11n); assert.equal(r.command[0].MakeProposal.action[0].ManageNeuron.id[0].id, 22n); });
test("current exclusions and future commands fail visibly", () => { assert.equal(commandAvailability("Disburse").enabled, false); assert.equal(commandAvailability("RefreshVotingPower").enabled, true); assert.equal(commandAvailability("Future").enabled, false); });
test("command and quorum boundary validation is explicit", () => { assert.equal(commandAvailability("Disburse",true).enabled,true); assert.equal(commandAvailability("DisburseToNeuron",true).enabled,true); assert.throws(()=>quorum(-1)); assert.throws(()=>quorum(16)); assert.throws(()=>quorum(1.5)); assert.throws(()=>buildNeuronManagementProposal({command:{kind:"Future"}})); });
test("following validation keeps raw distinctness", () => { assert.throws(() => projectedFollowing({targetId:"9",topic:1,followees:["1","1","2","3","4"],managers:[],committed:false})); assert.deepEqual(projectedFollowing({targetId:"9",topic:1,followees:["1","2","3","4","5"],managers:[],committed:false}), [1n,2n,3n,4n,5n]); });
test("following validation covers manager and committed boundaries", () => { assert.throws(()=>projectedFollowing({targetId:"9",topic:1,followees:["1","2","3","4"],managers:[],committed:false})); assert.throws(()=>projectedFollowing({targetId:"9",topic:1,followees:["1","2","3","4","9"],managers:[],committed:false})); assert.throws(()=>projectedFollowing({targetId:"9",topic:4,followees:["1","2"],managers:["1","2"],committed:true})); assert.throws(()=>projectedFollowing({targetId:"9",topic:4,followees:["1","2","7"],managers:["1","2","3"],committed:true})); });
test("failed simulation never submits", async () => { let called=false; const actor={simulate_manage_neuron:async()=>({Err:"no"}),manage_neuron:async()=>{called=true}}; const result=await simulateThenSubmit({actor,request:{},confirmed:true}); assert.equal(result.submitted,false); assert.equal(called,false); });
test("explicit confirmation gates submission", async () => { let called=false; const actor={simulate_manage_neuron:async()=>({Ok:null}),manage_neuron:async()=>{called=true;return {Ok:1n}}}; assert.equal((await simulateThenSubmit({actor,request:{},confirmed:false})).submitted,false); assert.equal(called,false); assert.equal((await simulateThenSubmit({actor,request:{},confirmed:true})).submitted,true); });
test("reward receiver classification preserves ambiguity", () => { assert.deepEqual(classifyReceiver([]),{kind:"NoReceiver"}); assert.deepEqual(classifyReceiver(["9"]),{kind:"SingleReceiver",id:"9"}); assert.deepEqual(classifyReceiver(["9","9"]),{kind:"AmbiguousReceiver"}); });
test("compliance variants and digests render deterministically", () => { assert.equal(variantName({StandardUpdateRequired:null}), "StandardUpdateRequired"); assert.equal(hexDigest(Uint8Array.from([0,15,255])), "000fff"); });
test("typed refresh errors are explicit", () => { assert.match(errorMessage({Cooldown:{retry_after_seconds:12n}}), /12/); assert.match(errorMessage({GlobalRateLimit:{retry_after_seconds:9n}}), /9/); assert.match(errorMessage({LowCycles:null}), /cycles/); assert.match(errorMessage({DuplicateInFlight:null}), /already running/); assert.match(errorMessage({ConcurrencyLimit:null}), /concurrency/); assert.equal(errorMessage({Upstream:"bounded error"}), "bounded error"); });
test("unknown and empty typed values render safely",()=>{assert.equal(variantName(null),"Unknown");assert.equal(errorMessage({Future:null}),"Future");});
test("canister hostname derivation rejects ambiguous local hosts", () => { assert.equal(canisterIdFromHostname("aaaaa-aa.icp0.io"), "aaaaa-aa"); assert.throws(() => canisterIdFromHostname("localhost")); });
test("anonymous actor construction uses the exact selected canister", async () => { const fakeAgent={}; const result=await createAnonymousActor({canisterId:"aaaaa-aa",createAgent:async()=>fakeAgent,createActor:(_factory,config)=>config}); assert.equal(result.agent,fakeAgent); assert.equal(result.canisterId,"aaaaa-aa"); });
test("anonymous actor uses SDK actor construction when only agent creation is injected", async()=>{const actor=await createAnonymousActor({canisterId:"aaaaa-aa",createAgent:async()=>({query:async()=>{},call:async()=>{}})});assert.ok(actor);});

class FakeNode { constructor(tag){this.tag=tag;this.children=[];this.textContent="";} append(...nodes){this.children.push(...nodes);} replaceChildren(...nodes){this.children=[...nodes];} }
test("safe DOM helpers never parse HTML and reject unsafe links", () => { const prior=globalThis.document; globalThis.document={createElement:(tag)=>new FakeNode(tag)}; try { const node=element("p","<img src=x onerror=alert(1)>","safe"); assert.equal(node.textContent,"<img src=x onerror=alert(1)>"); assert.equal(node.className,"safe"); const link=safeHttpsLink("safe","https://example.com/x"); assert.equal(link.rel,"noopener noreferrer"); assert.throws(()=>safeHttpsLink("bad","javascript:alert(1)")); const root=new FakeNode("main"); root.append(node); clear(root); assert.equal(root.children.length,0); } finally { globalThis.document=prior; } });
test("snapshot renderer emits complete safe rule tables", () => { const prior=globalThis.document; globalThis.document={createElement:(tag)=>new FakeNode(tag)}; try { const root=new FakeNode("main"); renderSnapshot(root,{stale_after_timestamp_seconds:100n,neuron_id:18422777432977120264n,overall_status:{NonCompliant:null},standard_version:"v",source_revision:"r",checked_at_timestamp_seconds:50n,evidence_digest:Uint8Array.from([1,2]),manager_ids:[1n,2n],quorum_threshold:[2],committed_topics:[4],rules:[{rule_id:"RULE",status:{Fail:null},summary:"<script>x</script>",observed:["bad"],expected:[],source:{method:"list_neurons",observed_at_seconds:50n}}],source_errors:["<img onerror=x>"]},101n); assert.equal(root.children[0].textContent,"Neuron 18422777432977120264"); assert.match(root.children[1].textContent,/STALE/); assert.ok(root.children.length>=5); } finally { globalThis.document=prior; } });
test("snapshot renderer labels fresh empty evidence without optional assumptions",()=>{const prior=globalThis.document;globalThis.document={createElement:(tag)=>new FakeNode(tag)};try{const root=new FakeNode("main");renderSnapshot(root,{stale_after_timestamp_seconds:100n,neuron_id:1n,overall_status:{Compliant:null},standard_version:"v",source_revision:"r",checked_at_timestamp_seconds:50n,evidence_digest:[],manager_ids:[],quorum_threshold:[],committed_topics:[],rules:[],source_errors:[]},99n);assert.match(root.children[1].textContent,/fresh/);}finally{globalThis.document=prior;}});
test("snapshot evidence summaries and warnings remain text-only",()=>{const prior=globalThis.document;globalThis.document={createElement:(tag)=>new FakeNode(tag)};try{const root=new FakeNode("main");renderSnapshot(root,{stale_after_timestamp_seconds:100n,neuron_id:1n,overall_status:{Indeterminate:null},standard_version:"v",source_revision:"r",checked_at_timestamp_seconds:50n,evidence_digest:[],manager_ids:[],quorum_threshold:[],committed_topics:[],rules:[],source_errors:[],summary_fields:[[{label:"<img onerror=x>",value:"<script>bad</script>"}]],warnings:[["<svg onload=x>"]]},99n);const text=JSON.stringify(root);assert.match(text,/<script>bad<\/script>/);assert.match(text,/<svg onload=x>/);}finally{globalThis.document=prior;}});
