import test from "node:test";
import assert from "node:assert/strict";
import { parseNeuronId, formatNeuronId, OMEGA_REJECT_NEURON_ID } from "../src/ids.js";
import { errorMessage, renderReport, variantName } from "../src/compliance-view.js";
import { createAnonymousActor, validatedCanisterId } from "../src/actor.js";
import { checkLive } from "../src/live-check.js";
import { clear, element, safeHttpsLink } from "../src/dom.js";

test("u64 IDs round trip without Number", () => { const id = parseNeuronId(OMEGA_REJECT_NEURON_ID); assert.equal(typeof id, "bigint"); assert.equal(formatNeuronId(id), OMEGA_REJECT_NEURON_ID); });
test("malformed IDs fail closed", () => { for (const id of ["", "0", "01", "+1", "-1", " 1", "1 ", "1.0", "1e2", "18446744073709551616"]) assert.throws(() => parseNeuronId(id)); });
test("build-time canister configuration is independent of the hostname", () => { assert.equal(validatedCanisterId("aaaaa-aa"), "aaaaa-aa"); assert.throws(() => validatedCanisterId("not a principal")); });
test("default build-time canister configuration is valid",()=>{assert.equal(validatedCanisterId(),"aaaaa-aa");assert.throws(()=>validatedCanisterId(7));});
test("anonymous actor uses the exact configured canister", async () => { const fakeAgent={}; const result=await createAnonymousActor({canisterId:"aaaaa-aa",createAgent:async()=>fakeAgent,createActor:(_factory,config)=>config}); assert.equal(result.agent,fakeAgent); assert.equal(result.canisterId,"aaaaa-aa"); });
test("anonymous actor supports SDK actor construction",async()=>{assert.ok(await createAnonymousActor({canisterId:"aaaaa-aa",createAgent:async()=>({query:async()=>{},call:async()=>{}})}));});
test("live success calls only check_neuron with bigint", async () => { let seen; const report={neuron_id:7n}; const result=await checkLive({check_neuron:async(id)=>{seen=id;return {Ok:report};}},"7"); assert.equal(seen,7n); assert.equal(result,report); });
test("each public error is explicit", async () => { for (const error of [{InvalidNeuronId:"bad"},{TemporarilyUnavailable:"wait"},{Upstream:"upstream"},{GlobalRateLimit:{retry_after_seconds:9n}},{LowCycles:null},{DuplicateInFlight:null},{ConcurrencyLimit:null}]) { const message=errorMessage(error); assert.ok(message.length); await assert.rejects(()=>checkLive({check_neuron:async()=>({Err:error})},"7")); } });
test("all overall statuses have stable names",()=>{for(const name of ["Compliant","NonCompliant","Indeterminate","StandardUpdateRequired"])assert.equal(variantName({[name]:null}),name);});

class FakeNode { constructor(tag){this.tag=tag;this.children=[];this.textContent="";} append(...nodes){this.children.push(...nodes);} replaceChildren(...nodes){this.children=[...nodes];} }
const report = (status="Compliant") => ({neuron_id:18422777432977120264n,overall_status:{[status]:null},standard_version:"v",source_revision:"r",checked_at_timestamp_seconds:50n,quorum_threshold:[3],target:[{known_neuron:[{id:1n,name:"<script>x</script>",description:["<img onerror=x>"],links:["javascript:bad","https://example.com/"]}],controller:[],hot_keys:[],not_for_profit:[false],dissolving:[false],dissolve_delay_seconds:[63072000n],effective_stake_e8s:[1n],voting_power_refreshed_timestamp_seconds:[1n],potential_voting_power:[1n],deciding_voting_power:[1n]}],managers:[{neuron_id:1n,known_neuron:[]}],committed_topics:[{topic:4,delegate_ids:[1n,2n,3n]}],non_committed_topics:[{topic:0,followee_ids:[2947465672511369n]}],controller:[],rules:[{rule_id:"RULE",status:{Pass:null},message:"<svg onload=x>",observed:[],expected:[],relevant_topic:[],related_neuron_ids:[]}],source_failures:[{method:"list_neurons",kind:{InvalidResponse:null},message:"<iframe>"}]});
test("safe DOM rendering preserves malicious text without parsing it", () => { const prior=globalThis.document; globalThis.document={createElement:(tag)=>new FakeNode(tag)}; try { const root=new FakeNode("main"); renderReport(root,report("NonCompliant")); const text=JSON.stringify(root); assert.match(text,/<script>x<\/script>/); assert.match(text,/<svg onload=x>/); assert.match(text,/Rejected unsafe URL/); } finally { globalThis.document=prior; } });
test("renderer covers reports without optional target or failures",()=>{const prior=globalThis.document;globalThis.document={createElement:(tag)=>new FakeNode(tag)};try{const root=new FakeNode("main"),value=report();value.target=[];value.source_failures=[];value.quorum_threshold=[];value.managers=[];value.committed_topics=[];value.non_committed_topics=[];renderReport(root,value);assert.match(JSON.stringify(root),/live consensus result/);}finally{globalThis.document=prior;}});
test("safe helpers reject non-HTTPS links and never parse HTML",()=>{const prior=globalThis.document;globalThis.document={createElement:(tag)=>new FakeNode(tag)};try{assert.equal(element("p","<b>x</b>").textContent,"<b>x</b>");assert.throws(()=>safeHttpsLink("bad","javascript:bad"));const root=new FakeNode("main");root.append(element("p","x"));clear(root);assert.equal(root.children.length,0);}finally{globalThis.document=prior;}});
