[package]
name = "dendrite-test-governance"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
dendrite-types = { version = "=0.1.0", path = "../../../crates/dendrite-types" }
ic-cdk.workspace = true
ic-clients = { version = "=0.1.0", path = "../../../crates/ic-clients" }
serde.workspace = true
