[package]
name = "dendrite"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candid.workspace = true
dendrite-types = { path = "../../crates/dendrite-types" }
ic-cdk.workspace = true
ic-clients = { path = "../../crates/ic-clients" }
ic-stable-structures.workspace = true
serde.workspace = true
